---
# Role        : ensure_reauth_privilege
# Description : Ensure re-authentication for privilege escalation is not disabled globally.
# Wazuh ID    : 35666

- name: "Ensure re-authentication for privilege escalation is not disabled globally"
  lineinfile:
    path: "{{ item }}"
    regexp: '^\\s*\\t*!authenticate'
    line: '!authenticate'
    state: absent
  loop: "{{ sudoers_files }}"
  when: ansible_facts.os_family == "Debian"
