---
# Role        : ensure_reauth_privilege
# Description : Ensure re-authentication for privilege escalation is not disabled globally.
# Wazuh ID    : 35666

- name: "Verify operating system is Debian/Ubuntu (apt-based)"
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'Ubuntu']
    fail_msg: >
      CRITICAL: This role only supports Debian/Ubuntu-based systems.
      Execution will STOP on this host because the OS family is not 'Debian'.
      Current value: {{ ansible_os_family | default('UNKNOWN') }}
    success_msg: "OS family verified as Debian or Ubuntu."

- name: "Ensure re-authentication for privilege escalation is not disabled globally"
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: '^\\s*\\t*!authenticate'
    line: '!authenticate'
    state: absent
  loop: "{{ sudoers_files }}"
  when: ansible_facts.os_family == "Debian"
