---
# defaults/main.yml
# Role         : disable_packet_redirects
# Description  : Ensure packet redirect sending is disabled.
#
# Default configuration for the disable_packet_redirects role

# Sysctl file path for network settings
sysctl_file_path: /etc/sysctl.d/60-netipv4_sysctl.conf

# Sysctl parameters to disable packet redirects
sysctl_parameters:
  - name: net.ipv4.conf.all.send_redirects
    value: "0"
  - name: net.ipv4.conf.default.send_redirects
    value: "0"
