---
galaxy_info:
  role_name: disable_rds
  author: Patricio Rojas Ortiz
  description: Ensure rds kernel module is not available (Wazuh ID 35606)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - kernel
    - modules

dependencies: []
