---
# defaults/main.yml
# Role         : configure_secure_icmp_redirects
# Description  : Ensure secure ICMP redirects are disabled.
#
# Default configuration for the secure_icmp_redirects role

sysctl_config_file: /etc/sysctl.d/60-secure-icmp-redirects.conf
