---
galaxy_info:
  role_name: enable_sustemd_timesync
  author: Patricio Rojas Ortiz
  description: Ensure systemd-timesyncd is enabled and running (Wazuh ID 35589)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

dependencies: []
