---
galaxy_info:
  role_name: disable_cramfs
  author: Patricio Rojas Ortiz
  description: Ensure mounting of cramfs filesystems is disabled (Wazuh 35500)
  license: Apache 2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - sysadmin

dependencies: []
