---
galaxy_info:
  role_name: configure_shadow_permissions
  author: Patricio Rojas Ortiz
  description: Ensure permissions on /etc/shadow- are configured (Wazuh ID 35765
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - authentication
    - filesystem

dependencies: []
