---
galaxy_info:
  role_name: disable_apport
  author: Patricio Rojas Ortiz
  description: Ensure Automatic Error Reporting is not enabled (Wazuh ID 35545)
  license: Apache 2.0
  namespace: ubuntu-server
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - ubuntu
    - apport
    - errorreporting

dependencies: []
