---
# defaults/main.yml
# Default variables for sshd_access_control role
# These values can be overridden by inventory or extra vars

# SSH access control configuration
# Only one of the following sets should be defined for clarity
# If both AllowUsers and AllowGroups are defined, both conditions must be met (AND logic)
ssh_access_allow_users: ['pro']
ssh_access_allow_groups: []
ssh_access_deny_users: [
    '_aided',
    '_apt',
    '_chrony',
    'backup',
    'bin',
    'daemon',
    'dhcpcd',
    'games',
    'irc',
    'list',
    'lp',
    'mail',
    'man',
    'messagebus',
    'news',
    'nobody',
    'postfix',
    'proxy',
    'root',
    'sshd',
    'sync',
    'system-network',
    'system-resolve',
    'systemd-timesync',
    'tcpdump',
    'uucp',
    'uuidd',
    'wazuh',
    'www-data',
]
ssh_access_deny_groups: []

# SSH configuration file paths
ssh_config_dir: /etc/ssh
ssh_config_file: /etc/ssh/sshd_config
ssh_config_include_dir: /etc/ssh/sshd_config.d

# Configuration file name for SSH access control
ssh_access_config_file: "{{ ssh_config_include_dir }}/99-ssh-access-control.conf"

# Service management
ssh_service_name: sshd
