---
remove_bloatware_packages_:
  #  - geoclue-2.0           # A package with a high dependency on the GNOME desktop shell.
  #  - nftables              # docker.io : Dependency with : containerd (>= 1.2.6-0ubuntu1~)
  - apache2-bin
  - avahi-daemon
  - avahi-utils
  - bind9
  - bluetooth
  - bluez
  - bluez-cups
  - bluez-obexd
  - cups
  - cups-browsed
  - cups-bsd
  - cups-client
  - cups-common
  - cups-daemon
  - cups-filters-core-drivers
  - cups-pk-helper
  - cups-ppdc
  - deja-dup
  - dovecot-imapd
  - dovecot-pop3d
  - duplicity
  - evolution
  - evolution-data-server
  - ftp
  - gnome-bluetooth-sendto
  - gnome-characters
  - gnome-maps
  - gnome-remote-desktop
  - gnome-tour
  - gnome-weather
  - inetutils-telnet
  - inetutils-telnetd
  - iptables-persistent
  - isc-dhcp-server
  - ldap-utils
  - libvirt-daemon*
  - nfs-kernel-server
  - nginx
  - nis
  - open-iscsi
  - openvpn
  - remmina
  - rsh-client
  - rsh-server
  - samba
  - slapd
  - snmpd
  - systemd-resolved
  - talk
  - telnet*
  - tftp-hpa
  - tftpd-hpa
  - tnftp
  - tnftp                    # This removes ubuntu-standard (ubuntu-standard is a metapackage)
  - tracker                  # Dependency with GNOME Files (default file manager)
  - vim
  - vim-common
  - vsftpd
  - xinetd
#  - yelp                    # Dependencias with gnome-user-docs ubuntu-desktop ubuntu-desktop-minimal ubuntu-docs yelp
