profile: production
exclude_paths:
  - .git/
  - build/
  - dist/
  - .molecule/
  - node_modules/
  - .idea/

strict: true
use_default_rules: true
loop_var_prefix: "^(__|{role}_)"
var_naming_pattern: "^[a-z_][a-z0-9_]*$"

enable_list:
  - args
  - empty-string-compare
  - no-log-password
  - no-same-owner
  - name[prefix]
  - galaxy-version-incorrect
  - yaml
  - no-changed-when
  - command-instead-of-module
  - risky-shell-pipe

warn_list:
  - fqcn-builtins

offline: true
task_name_prefix: "{stem} | "

skip_list:
  - var-naming[no-role-prefix]
