---
galaxy_info:
  role_name: disable_tftp
  author: Patricio Rojas Ortiz
  description: Ensure tftp server services are not in use. (Wazuh ID 35576)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - tftp
    - removal

dependencies: []
