---
# Role        : enable_apparmor
# Description : Ensure AppArmor is enabled in the bootloader configuration
# Wazuh ID    : 35537

- name: "Check if /boot/grub/grub.cfg exists"
  ansible.builtin.stat:
    path: /boot/grub/grub.cfg
  register: grub_cfg_stat

- name: Check variable grub_cfg_stat
  ansible.builtin.debug:
    msg: "grub_cfg_stat.stat.exists: {{ grub_cfg_stat.stat.exists }}"

- name: "Show message if grub.cfg not found"
  ansible.builtin.debug:
    msg: "/boot/grub/grub.cfg Not applicable"
  when: not grub_cfg_stat.stat.exists

# VM does not have a bootloader.
- name: "Check if /boot/grub/grub.cfg exists"
  ansible.builtin.stat:
    path: /boot/grub/grub.cfg
  register: grub_cfg_exists
  failed_when: false

- name: "Configure grub (only if file exists)"
  become: true
  when: grub_cfg_exists.stat.exists | bool
  notify: Update grub
  block:

    - name: "Read the current information of /etc/default/grub"
      ansible.builtin.slurp:
        path: "{{ configure_grub_path_default_grub }}"
      register: grub_file
      changed_when: false

    # Solving Wazuh id 35537 Ensure AppArmor is enabled in the bootloader configuration.
    - name: "Ensure AppArmor is enabled in the bootloader configuration."
      ansible.builtin.lineinfile:
        path: "{{ configure_grub_path_default_grub }}"
        regexp: '^GRUB_CMDLINE_LINUX="((?!.*{{ apparmor_kernel_params }}).*)"$'
        line: 'GRUB_CMDLINE_LINUX="\1 {{ apparmor_kernel_params }}"'
        backrefs: true
