---
# Role        : sshd_access_control
# Description : Ensure sshd access is configured.
# Wazuh ID    : 35643

- name: "Gather package facts to detect sshd"
  ansible.builtin.package_facts:
    manager: auto

- name: "Check if openssh-server package is installed"
  ansible.builtin.set_fact:
    openssh_server_package_installed: "{{ 'openssh-server' in ansible_facts.packages }}"

- name: "Task block when openssh-server is installed"
  when: openssh_server_package_installed | bool
  become: true
  block:

    - name: "Ensure SSH access control configuration directory exists"
      ansible.builtin.file:
        path: "{{ ssh_config_include_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    # was installed in ubuntu 24.04 the module: uv add ansible[jinja2]
    - name: "Ensure SSH access control configuration file is properly configured"
      become: true
      ansible.builtin.template:
        src: ssh_access_control.conf.j2
        dest: "{{ ssh_access_config_file }}"
        owner: root
        group: root
        mode: "0600"
        validate: "/usr/sbin/sshd -t -f %s"
      notify: Restart SSH Service

    - name: "Ensure SSH service is enabled and running"
      ansible.builtin.service:
        name: "{{ ssh_service_name }}"
        state: started
        enabled: true

- name: Verify if openssh-server is installed
  ansible.builtin.debug:
    msg: "openssh-server IS NOT installed on this host. SSH configuration tasks are skipped."
  when: "'openssh-server' not in ansible_facts.packages"
