---
# Role        : sshd_access_control
# Description : Ensure sshd access is configured (Wazuh ID 35643)
# Wazuh ID    : 35643

- name: "Ensure SSH access control configuration directory exists"
  ansible.builtin.file:
    path: "{{ ssh_config_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

# was installed in ubuntu 24.04 the module: uv add ansible[jinja2]
- name: "Ensure SSH access control configuration file is properly configured"
  ansible.builtin.template:
    src: ssh_access_control.conf.j2
    dest: "{{ ssh_access_config_file }}"
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart SSH Service

- name: "Ensure SSH service is enabled and running"
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: started
    enabled: true
