---
# defaults/main.yml
# Safe defaults for the enable_apparmor role
# These values can be overridden by user variables

apparmor_grub_cmdline_params: "apparmor=1 security=apparmor"

apparmor_grub_file: /etc/default/grub
apparmor_grub_update_command: /usr/sbin/update-grub
