---
# defaults/main.yml
# Default variables for the enforce_apparmor role
# These values can be overridden by inventory or playbook vars

# Mode to set AppArmor profiles: 'enforce' or 'complain'
apparmor_profile_mode: enforce

# Path to AppArmor profiles directory
apparmor_profiles_dir: /etc/apparmor.d

# Whether to reload AppArmor after changing profile modes
apparmor_reload_profiles: true

apparmor_enforce_profiles: []
apparmor_complain_profiles: []
apparmor_ignore_profiles: []
