---
galaxy_info:
  role_name: configure_chrony_user
  author: Patricio Rojas Ortiz
  description: Ensure chrony is running as user _chrony (Wazuh ID 35591)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - time
    - chrony
    - ntp

dependencies: []
