---
# defaults/main.yml
# Default variables for disable_dccp role
dccp_modprobe_conf_file: /etc/modprobe.d/dccp.conf
dccp_modprobe_blacklist_content: |
  #
  # Description : Ensure the DCCP kernel module is not available
  # Wazuh ID    : 35604
  # Generated   : {{ lookup('pipe', 'date "+%Y-%m-%d_%H:%M:%S"') }}
  #
  install dccp /bin/false
  blacklist dccp
