---
galaxy_info:
  role_name: restrict_core_dumps
  author: Patricio Rojas Ortiz
  description: Disable core dumps to prevent sensitive memory information leakage (Wazuh 35543)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - sysadmin
    - memory
    - hardening

dependencies: []
