---
galaxy_info:
  role_name: configure_bootloader_access
  author: Patricio Rojas Ortiz
  description: Ensure access to bootloader config is configured Wazuh ID 35541
  license: MIT

  min_ansible_version: "2.16"

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - security
    - hardening
    - cron
    - permissions
    - compliance

dependencies: []
