---
# Role        : sshd_disable_forwarding
# Description : Ensure sshd DisableForwarding is enabled
# Wazuh ID    : 35647

- name: "Ensure DisableForwarding is set to yes in sshd_config"
  ansible.builtin.lineinfile:
    path: "{{ sshd_config_file }}"
    regexp: '^\s*#?\s*[Dd]isable[Ff]orwarding.*$'
    line: "{{ sshd_disable_forwarding_line }}"
    state: present
    owner: root
    group: root
    mode: "0644"
    insertafter: EOF
  notify: Restart sshd

- name: "Check if 'disableforwarding yes' exists in sshd_config"
  ansible.builtin.command: >
    grep -Ei '^\s*disableforwarding\s' /etc/ssh/sshd_config
  register: disableforwarding_check
  changed_when: false
  failed_when: false

- name: "Display a red warning if 'disableforwarding no' has not been"
  ansible.builtin.debug:
    msg: "\u001b[31m[WARNING] 'disableforwarding no' is still present. Continuing with the role execution.\u001b[0m"
  when: disableforwarding_check.rc != 0

