---
galaxy_info:
  role_name: enable_cron
  author: Patricio Rojas Ortiz
  description: Ensure cron daemon is enabled and active (Wazuh ID 35593)
  license: Apache 2.0
  namespace: ubuntu-server
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - sysadmin
    - scheduling
    - cron

dependencies: []
