---
galaxy_info:
  role_name: configure_mail_agent_local_only
  author: Patricio Rojas Ortiz
  description: Ensure mail transfer agent is configured for local-only mode. (Wazuh ID 35581)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - security
    - audit
    - compliance
    - sysadmin
    - postfix
    - mail

dependencies: []
