---
# Role        : disable_usb_storage
# Description : Handlers for the disable_usb_storage role

- name: Update initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u
  register: initramfs_update
  changed_when: initramfs_update.rc == 0
  failed_when: false
