---
galaxy_info:
  role_name: enforce_apparmor
  author: Patricio Rojas Ortiz
  description: Enforce or complain AppArmor profiles system-wide (Wazuh ID 35760)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - security
    - apparmor
    - compliance
    - sysadmin

dependencies: []
