---
galaxy_info:
  role_name: enable_aslr
  author: Patricio Rojas Ortiz
  description: Enable Address Space Layout Randomization (ASLR) to reduce exploitability of memory corruption vulnerabilities
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - hardening
    - kernel

dependencies: []
