---
# Role        : enable_apparmor
# Description : Handlers for the enable_apparmor role

- name: "Update grub"
  ansible.builtin.command: update-grub
  become: true
  register: result
  changed_when: false
