---
galaxy_info:
  role_name: disable_dns_server
  author: Patricio Rojas Ortiz
  description: Ensure DNS server services are not in use (Wazuh ID 35564)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - dns
    - bind9
    - network

dependencies: []
