---
# Role        : disable_cramfs
# Description : Ensure mounting of cramfs filesystems is disabled.
# Wazuh ID    : 35500

- name: "Ensure modprobe configuration directory exists"
  ansible.builtin.file:
    path: /etc/modprobe.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "Check if cramfs kernel module is loaded"
  ansible.builtin.command:
    cmd: lsmod | grep {{ cramfs_kernel_module }}
  register: modprobe_check
  changed_when: false
  failed_when: modprobe_check.rc != 1 and modprobe_check.rc != 0

- name: "Unload loaded kernel modules"
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail
      modprobe -r {{ item.item }} || rmmod {{ item.item }} || true
  register: unload_result
  changed_when: false
  when: item.rc == 0
  loop: "{{ module_loaded.results }}"

- name: "Ensure cramfs is blacklisted in modprobe.d"
  ansible.builtin.copy:
    dest: "{{ cramfs_modprobe_conf_file }}"
    content: "{{ modprobe_blacklist_content }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart System

- name: "Ensure no other conf files are enabling cramfs"
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/*.conf
    regexp: '^install\s+{{ cramfs_kernel_module }}\s+/bin/true$|^blacklist\s+{{ cramfs_kernel_module }}$'
    state: absent
