---
# Role        : disable_cramfs
# Description : Ensure mounting of cramfs filesystems is disabled.
# Wazuh ID    : 35500

- name: "Check if cramfs kernel module is loaded"
  ansible.builtin.command:
    cmd: lsmod | grep {{ cramfs_kernel_module }}
  register: modprobe_check
  changed_when: false
  failed_when: modprobe_check.rc != 1 and modprobe_check.rc != 0

- name: "Remove cramfs kernel module if loaded"
  ansible.builtin.command:
    cmd: modprobe -r {{ cramfs_kernel_module }} && rmmod {{ cramfs_kernel_module }}
  when: modprobe_check.rc == 0
  register: modprobe_output
  changed_when: "'Changed:' in modprobe_output.stdout"

- name: "Ensure cramfs is blacklisted in modprobe.d"
  ansible.builtin.copy:
    dest: "{{ cramfs_modprobe_conf_file }}"
    content: "{{ modprobe_blacklist_content }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart System

- name: "Ensure no other conf files are enabling cramfs"
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/*.conf
    regexp: '^install\s+{{ cramfs_kernel_module }}\s+/bin/true$|^blacklist\s+{{ cramfs_kernel_module }}$'
    state: absent
