---
# Role: disable_hfsplus
# Description: Handlers for the disable_hfsplus role

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  when: ansible_facts.os_family == "Debian"
  register: initramfs_result
  changed_when: true
  failed_when: false
