---
galaxy_info:
  role_name: enable_apparmor
  author: Patricio Rojas Ortiz
  description: Enable AppArmor in bootloader configuration for Ubuntu 24.04 (Wazuh 35537)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - apparmor
    - compliance
    - sysadmin
    - audit

dependencies: []
