---
galaxy_info:
  role_name: sshd_macs
  author: Patricio Rojas Ortiz
  description: Ensure sshd MACs are configured (Wazuh ID 35654)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - security
    - ssh
    - compliance
    - sysadmin

dependencies: []
