---
# Role        : configure_group_permissions
# Description : Ensure permissions on /etc/group are configured (Wazuh ID 35763)
# Wazuh ID    : 35763

- name: "Verify operating system is Debian/Ubuntu (apt-based)"
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'Ubuntu']
    fail_msg: >
      CRITICAL: This role only supports Debian/Ubuntu-based systems.
      Execution will STOP on this host because the OS family is not 'Debian'.
      Current value: {{ ansible_os_family | default('UNKNOWN') }}
    success_msg: "OS family verified as Debian or Ubuntu."

- name: "Check if /etc/group exists"
  ansible.builtin.stat:
    path: "{{ etc_group_path }}"
  register: file_stat

- name: "Debug variable check file exists"
  ansible.builtin.debug:
    msg: "debug variable if /etc/group exists value : {{ file_stat }}"
  changed_when: false

- name: "Ensure /etc/group has correct ownership and permissions (u-x,go-wx)"
  ansible.builtin.file:
    path: "{{ etc_group_path }}"
    owner: "{{ etc_group_owner }}"
    group: "{{ etc_group_group }}"
    mode: "{{ etc_group_mode }}"
  when: file_stat.stat.exists
