---
# Role        : configure_group_permissions
# Description : Ensure permissions on /etc/group are configured (Wazuh ID 35763)
# Wazuh ID    : 35763

- name: "Check if /etc/group exists"
  ansible.builtin.stat:
    path: "{{ etc_group_path }}"
  register: file_stat

- name: "Debug variable check file exists"
  ansible.builtin.debug:
    msg: "debug variable if /etc/group exists value : {{ file_stat }}"
  changed_when: false

- name: "Ensure /etc/group has correct ownership and permissions (u-x,go-wx)"
  ansible.builtin.file:
    path: "{{ etc_group_path }}"
    owner: "{{ etc_group_owner }}"
    group: "{{ etc_group_group }}"
    mode: "{{ etc_group_mode }}"
  when: file_stat.stat.exists
