---
# Role        : disable_cramfs
# Description : Handlers for the disable_cramfs role.

- name: "Update initramfs"
  ansible.builtin.command: update-initramfs -u
  args:
    creates: /boot/initrd.img-$(uname -r)
  when: ansible_facts.os_family == "Debian"
  changed_when: true
  failed_when: false
