---
# Role: configure_chrony_user
# Description: Handlers for the configure_chrony_user role

- name: Purge unused dependencies
  ansible.builtin.apt:
    autoremove: true
    purge: true
  register: cleanup_result
  changed_when: false
