---
# Role        : configure_timesyncd_authorized_servers
# Description : Handlers for configure_timesyncd_authorized_servers role

- name: Reload systemd-timesyncd
  become: true
  ansible.builtin.systemd:
    name: "{{ timesyncd_service_name }}"
    state: restarted
    daemon_reload: true
