---
galaxy_info:
  role_name: configure_icmp_ignore_bogus_error_responses
  author: Patricio Rojas Ortiz
  description: Ensure bogus icmp responses are ignored. (Wazuh ID 35610)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - network
    - compliance
    - sysctl

dependencies: []
