---
galaxy_info:
  role_name: disable_user_list_gdm
  author: Patricio Rojas Ortiz
  description: Ensure GDM disable-user-list option is enabled.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - buster    # 10
        - bullseye  # 11
        - bookworm  # 12
dependencies: []
