---
# defaults/main.yml
# Role         : disable_tipc
# Description  : Ensure TIPC kernel module is disabled (Wazuh ID 35605)
#
# Default configuration for the `disable_tipc` role

tipc_modprobe_conf_path: /etc/modprobe.d/tipc.conf
modprobe_blacklist_content: |
  #
  # Description : Disable the tipc kernel module to prevent mounting of tipc filesystems
  # Wazuh ID    : 35605
  # Generated   : {{ lookup('pipe', 'date "+%Y-%m-%d_%H:%M:%S"') }}
  #
  install tipc /bin/false
  blacklist tipc


  # Enable/disable the role (can be overridden via group_vars or host_vars)
disable_tipc_enabled: true
