---
galaxy_info:
  role_name: configure_remote_login_banner
  author: Patricio Rojas Ortiz
  description: Ensure local login warning banner is configured properly.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - buster    # 10
        - bullseye  # 11
        - bookworm  # 12
dependencies: []
