---
galaxy_info:
  role_name: configure_local_login_banner
  author: Patricio Rojas Ortiz
  description: Ensure local login warning banner is configured properly (Wazuh ID 35547)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - banner
    - warning
    - login
    - ubuntu
    - nist
    - pci
    - fedramp

dependencies: []
