---
# Role: configure_bootloader_access
# Description: Ensure access to bootloader config is configured
# Wazuh ID: 35541
#
# Why It's Not Applicable to Containers
#  Containers typically do not have a traditional bootloader (like GRUB) or a persistent /boot partition.
# The /boot directory in containers is often ephemeral or absent.
# The rule relies on stat checks on /boot/grub/grub.cfg, which usually does not exist in containerized environments.
#


- name: "Check if /boot/grub/grub.cfg exists"
  ansible.builtin.stat:
    path: "{{ boot_grub_cfg_path }}"
  register: grub_stat

- name: "Set secure permissions for /boot/grub/grub.cfg if it exists"
  ansible.builtin.file:
    path: "{{ boot_grub_cfg_path }}"
    mode: "0600"                                       # chmod u-x,go-rwx /boot/grub/grub.cfg
    owner: root                                        # chmod root:root /boot/grub/grub.cfg
    group: root
    state: file
  when: grub_stat.stat.exists
