---
galaxy_info:
  role_name: sshd_kexalgorithms
  author: Patricio Rojas Ortiz
  description: Ensure sshd KexAlgorithms is configured (Wazuh ID 35651)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - ssh
    - compliance
    - crypto
    - encryption

dependencies: []
