---
galaxy_info:
  role_name: sudo_pty
  author: Patricio Rojas Ortiz
  description: Ensure sudo commands use pty to prevent background processes from escaping sudo session (Wazuh ID 35663)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - sudo
    - pty
    - hardening

dependencies: []
