---
# Role: file_permission
# Description: Set permissions on files/directories based on Wazuh recommendations.
#


# Wazuh ID 33052 - Ensure permissions on /etc/issue are configured
- name: "Check if /etc/issue exists"
  ansible.builtin.stat:
    path: /etc/issue
  register: etc_issue_stat

- name: "Set secure permissions for /etc/issue if it exists"
  ansible.builtin.file:
    path: /etc/issue
    mode: "0644" # chmod u-x,go-wx $(readlink -e /etc/issue)
    owner: root
    group: root
    state: file
  when: etc_issue_stat.stat.exists

# Wazuh ID 33053 - Ensure permissions on /etc/issue.net are configured
- name: "Check if /etc/issue.net exists"
  ansible.builtin.stat:
    path: /etc/issue.net
  register: etc_issue_net_stat

- name: "Set secure permissions for /etc/issue.net if it exists"
  ansible.builtin.file:
    path: /etc/issue.net
    mode: "0644" # chmod u-x,go-wx $(readlink -e /etc/issue.net)
    owner: root
    group: root
    state: file
  when: etc_issue_net_stat.stat.exists

# Additional file permissions
- name: "Check if /etc/cups/cupsd.conf exists"
  ansible.builtin.stat:
    path: /etc/cups/cupsd.conf
  register: cupsd_conf_stat

- name: "Set secure permissions for /etc/cups/cupsd.conf"
  ansible.builtin.file:
    path: /etc/cups/cupsd.conf
    mode: "0700"
    owner: root
    group: root
  when: cupsd_conf_stat.stat.exists

- name: "Check if /etc/sysctl.conf exists"
  ansible.builtin.stat:
    path: /etc/sysctl.conf
  register: sysctl_conf_stat

- name: "Set secure permissions for /etc/sysctl.conf"
  ansible.builtin.file:
    path: /etc/sysctl.conf
    state: touch
    mode: "0600"
    owner: root
    group: root
  when: sysctl_conf_stat.stat.exists

- name: "Check if /usr/bin/as exists"
  ansible.builtin.stat:
    path: /usr/bin/as
  register: as_stat

- name: "Set secure permissions for /usr/bin/as"
  ansible.builtin.file:
    path: /usr/bin/as
    mode: "0444"
    owner: root
    group: root
  when: as_stat.stat.exists
