---
galaxy_info:
  role_name: sshd_logingracetime
  author: Patricio Rojas Ortiz
  description: Ensure sshd LoginGraceTime is configured (Wazuh ID 35652)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - ssh
    - compliance
    - sysadmin
    - hardening

dependencies: []
