---
galaxy_info:
  role_name: disable_rsync
  author: Patricio Rojas Ortiz
  description: Ensure rsync services are not in use.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - buster    # 10
        - bullseye  # 11
        - bookworm  # 12
dependencies: []
