---
galaxy_info:
  role_name: disable_nfs
  author: Patricio Rojas Ortiz
  description: Ensure network file system services are not in use (Wazuh ID 35569)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - nfs
    - filesystem
    - ubuntu

dependencies: []
