# Default banner text – override in inventory or playbook if needed
gdm_banner_text: "Authorized users only. All activity may be monitored and reported."

# Enable the banner (boolean)
gdm_banner_enable: true

# Path to the system‑wide dconf database
gdm_dconf_profile_path: /etc/dconf/profile/gdm
gdm_dconf_db_path:  /etc/dconf/db/gdm.d/
gdm_dconf_db_path_and_file: /etc/dconf/db/gdm.d/01-banner-message

# File that CIS‑CAT checks against
gdm_greeter_defaults: /etc/gdm3/greeter.dconf-defaults
