---
# Role        : sshd_disable_forwarding
# Description : Handlers for sshd_disable_forwarding role

- name: Restart sshd
  ansible.builtin.systemd:
    name: "{{ sshd_service_name }}"
    state: restarted
    daemon_reload: true
