---
galaxy_info:
  role_name: configure_secure_icmp_redirects
  author: Patricio Rojas Ortiz
  description: Ensure secure ICMP redirects are not accepted. (Wazuh ID 35613)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - security
    - audit
    - compliance
    - sysadmin
    - kernel
    - networking

dependencies: []
