---
galaxy_info:
  role_name: configure_motd
  author: Patricio Rojas Ortiz
  description: Ensure message of the day is configured properly and complies with security policies (Wazuh ID 35546)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - linux
    - ubuntu
    - motd
    - banners

dependencies: []
