---
# Role        : uninstall_prelink
# Description : Ensure prelink is not installed
# Wazuh ID    : 35544

- name: "Verify operating system is Debian/Ubuntu (apt-based)"
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'Ubuntu']
    fail_msg: >
      CRITICAL: This role only supports Debian/Ubuntu-based systems.
      Execution will STOP on this host because the OS family is not 'Debian'.
      Current value: {{ ansible_os_family | default('UNKNOWN') }}
    success_msg: "OS family verified as Debian or Ubuntu."

- name: "Ensure prelink is not installed"
  ansible.builtin.apt:
    name: "{ prelink_package_name }"
    state: absent
    purge: true
    autoremove: true
  register: prelink_uninstall_result
  changed_when: prelink_uninstall_result is changed and prelink_uninstall_result.msg is not none

- name: "Verify prelink is not installed"
  ansible.builtin.command: dpkg-query -W prelink
  register: prelink_check_result
  changed_when: false | bool
  failed_when: prelink_check_result.rc == 0
