---
galaxy_info:
  role_name: disable_wireless
  author: Patricio Rojas Ortiz
  description: Ensure wireless interfaces are disabled.(Wazuh 35602 rule).
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - buster    # 10
        - bullseye  # 11
        - bookworm  # 12
  galaxy_tags: [security, wireless, modules, disable]
dependencies: []
