---
galaxy_info:
  role_name: enable_chrony
  author: Patricio Rojas Ortiz
  description: Ensure chrony is enabled and running (Wazuh ID 35592)
  license: Apache 2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance

dependencies: []
