---
galaxy_info:
  role_name: disable_unsafe_filesystem_modules
  author: Patricio Rojas Ortiz
  description: Disable unsafe filesystem kernel modules (CVE-motivated) by unloading and preventing future loading via modprobe configuration.
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - kernel
    - modules
    - cve

dependencies: []
