---
galaxy_info:
  role_name: sshd_access_control
  author: Patricio Rojas Ortiz
  description: Ensure sshd access is configured (Wazuh ID 35643)
  license: Apache 2.0
  namespace: ubuntu-server
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - ssh
    - compliance
    - sysadmin

dependencies: []
