---
galaxy_info:
  role_name: configure_opassswd_permissions
  author: Patricio Rojas Ortiz
  description: Ensure permissions on /etc/security/opasswd are configured Wazud ID 35770
  license: MIT

  min_ansible_version: "2.16"

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - security
    - hardening
    - cron
    - permissions
    - compliance

dependencies: []
