---
galaxy_info:
  role_name: sshd_permitemptypasswords_disabled
  author: Patricio Rojas Ortiz
  description: Ensure sshd PermitEmptyPasswords is disabled (Wazuh ID 35658)
  license: Apache 2.0
  namespace: ubuntu-server
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - ssh
    - authentication
    - hardening

dependencies: []
