---
galaxy_info:
  role_name: disable_snmp
  author: Patricio Rojas Ortiz
  description: Ensure SNMP services are not in use (Wazuh ID 35575)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - snmp
    - network
    - disable

dependencies: []
