---
# Role: sshd_access_control
# Description: Handlers for the sshd_access_control role

- name: Restart SSH Service
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: restarted
