---
galaxy_info:
  author: Patricio Rojas Ortiz
  description: Ensure /etc/shadow exists with correct permissions on Ubuntu
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - system
    - shadow
    - ubuntu
dependencies: []
