---
galaxy_info:
  role_name: disable_xinetd
  author: Patricio Rojas Ortiz
  description: Disable and remove the xinetd super-server to reduce attack surface. (Wazuh ID 35579)
  license: Apache 2.0
  namespace: security
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - compliance
    - sysadmin
    - services

dependencies: []
