---
# defaults/main.yml
# Role        : disable_overlayfs
# Description : Ensure overlay filesystem is disabled.

disable_overlayfs_enabled: true
overlay_unload_if_loaded: true
disable_overlayfs_blacklist_file: /etc/modprobe.d/disable-overlay.conf
disable_overlayfs_modules:
  - overlay
  - overlayfs

modprobe_blacklist_content: |
  #  
  # Role        : disable_overlaysfs
  # Description : Ensure overlay filesystem is disabled
  # Wazuh ID    : 35505
  # Generated   : {{ lookup('pipe', 'date "+%Y-%m-%d_%H:%M:%S"') }}
  #

  {% for module in disable_overlayfs_modules %}
  install {{ module }} /bin/false
  blacklist {{ module }}

  {% endfor %}
