---
galaxy_info:
  role_name: sshd_ignore_rhosts
  author: Patricio Rojas Ortiz
  description: Ensure sshd IgnoreRhosts is enabled (Wazuh ID 35650)
  license: Apache 2.0
  namespace: ubuntu-server
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - ssh
    - compliance
    - sysadmin

dependencies: []
